apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  serviceName: "mongodb-headless"
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      project: roboshop
      environment: {{ .Values.statefulset.environment }}
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        environment: {{ .Values.statefulset.environment }}
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.statefulset.image }}
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop"
      resources:
        requests:
          storage: 1Gi